### ISSUE TITLE
Vabandust, mis asi see Riiul on?

### ISSUE THREAD

**Issue by jubejuss** [tluhk/Riiul#1]

**Comment by mrtrvl** [comment]
Riiul on eelmise valikpraktika ajal alustatud ja praegu diplomitöö raames arendatav platvorm Haapsalu kolledžis tehtud diplomitööde näitamiseks/tutvustamiseks majavälistele inimestele.
Tegemist on päris vana probleemiga, mida on üritatud juba mitu korda lahendada kuid siiani ei ole see väga hästi õnnestunud. Hetkel on olukord selline, et platvorm on testimisfaasis ja loodetavasti saab mõne kuu jooksul kasutusvalmis.
Seni on olnud rakenduse kood arendaja isiklikus repositooriumis, see repsoitoorium siin on üheks esimeseks sammuks eesmärgiga koondada Haapsalu kolledžiga seotud rakenduste kood ühe organisatsiooni konto alla kokku.

**Comment by kristjantoots** [comment]
@mrtrvl ehk ei peaks see repositoorium praeguses staadiumis olema `public`, vaid hoopis `private`?

**Comment by mrtrvl** [comment]
`public` on sellepärast, et `private` repositooriumiga ei ole meil hetkel võimalik `wiki`-t kasutada.
